removed section talking about v5 - updated resource links
learn-co-curriculum/react-hooks-react-router-intro pull request #4
Opened 2023-07-20 23:04 UTC by Matt-Eva

2023-07-26 14:01 UTC, lizbur10 requested changes
Looks good!

2023-07-26 14:01 UTC, lizbur10 commented on README.md
> +[react-router]: https://reactrouter.com/en/main/start/tutorial
I think it might make more sense to link to the main page rather than the tutorial here since they use Vite in the tutorial. When we do the bigger update we can switch to this link. Or maybe by then they'll add a more beginner friendly getting started page

2023-07-28 21:59 UTC, Matt-Eva commented
Suggestions reviewed and implemented!

2023-08-29 00:23 UTC, AlveeM approved these changes

2023-08-29 15:05 UTC, Matt-Eva commented on README.md
> +[react-router]: https://reactrouter.com/en/main/start/tutorial
Implemented!

2023-10-03 12:32 UTC, merged